### ISSUE TITLE
Code coverage report

### ISSUE THREAD

**Issue by bekbeis** [olofk/serv#124]
Hi,

Do you guys have any reports related to coverage of your verification infrastructure? In other words, how good/mature is your verification environment?

Thanks!

**Comment by olofk** [comment]
No code coverage reports. The main methods for verification has been formal verification through riscv-formal, the RISC-V compliance tests, user programs running in simulation or on FPGA and successful tapeouts.

**Comment by bekbeis** [comment]
Thanks!
