### ISSUE TITLE
Run on hardware error

### ISSUE THREAD

**Issue by Martoni** [olofk/serv#13]
I can't generate serv soc for hardware as described in README : 

```
$ cd $SERV/workspace
$ fusesoc run --target=tinyfpga_bx servant
ERROR: Conflicting requirements:
Requirements: 'servant == 0-0' <- 'fusesoc_utils_generators >= 0-0'
    +servant-0-0 was ignored because it depends on missing packages
Requirements: 'servant == 0-0'
    Install command rule (+servant-0-0)

Failed to resolve dependencies for servant
```

Same for Icebreaker.

**Comment by olofk** [comment]
Oh, right. It depends on cores from the FuseSoC base library. Run `fusesoc library add fusesoc-cores https://github.com/fusesoc/fusesoc-cores` to add the library to that workspace, or `fusesoc library add --global fusesoc-cores https://github.com/fusesoc/fusesoc-cores` to have it accessible from all your workspaces

**Comment by olofk** [comment]
Need to update the docs to mention this

**Comment by Martoni** [comment]
I updated it in this pull https://github.com/olofk/serv/pull/12

**Comment by Martoni** [comment]
All commands described on README are ok for me now.
