### ISSUE TITLE
Versions with different bit-widths for SERV

### ISSUE THREAD

**Issue by Khaiduy** [olofk/serv#137]
Hi, I know that QERV is a 4-bit version of SERV but is there a 32-bit version of SERV that can be used to evaluate the trade-off between serial and parallel designs?

**Comment by olofk** [comment]
There is no 32-bit fully parallel (or PERV, as I like to call it) version of SERV planned. There is an 8-bit version (HERV) in the works, but du to some internal assumptions it will be much more complicated to adapt SERV to wider than 8 bits. I would recommend comparing against another small 32-bit core instead, like femtorv32.

**Comment by Khaiduy** [comment]
Thank you for your suggestion. I will look for the other cores.
