### ISSUE TITLE
Broken video links

### ISSUE THREAD

**Issue by modrobert** [olofk/serv#76]
The video links in README.md for "introduction to SERV" and "SERV : RISC-V for a fistful of gates" seems to be broken (assuming diode.zone host is down).

**Comment by olofk** [comment]
Thanks for reporting. diode.zone is confirmed to be down. Hope to find out soon how long it will stay down. In the meantime you can find the first video here https://drive.google.com/file/d/1H3Ne0fHPxMlATZxCtUXgg3_pSSo-Kw2u/view?usp=sharing and the second one here https://www.youtube.com/watch?v=Nh-9xfK8Q1g

**Comment by modrobert** [comment]
Thanks for the working links.

**Comment by Ashwin-Rajesh** [comment]
This seems to have been fixed now with diode.zone coming back online

**Comment by olofk** [comment]
Yes! Thanks for the reminder. Closing
