### ISSUE TITLE
Add a step for yosysSynthesisReport() to Jenkinsfile 

### ISSUE THREAD

**Issue by Nancy-Chauhan** [olofk/serv#8]
Extend the use case of yosysSynthesisReport() to serv project from Librecores pipeline library : https://github.com/librecores/librecores-pipeline-lib

Example for Reference : https://github.com/openrisc/mor1kx/blob/master/Jenkinsfile , 
https://ci.librecores.org/job/Projects/job/OpenRISC/job/mor1kx/job/master/plot/Resource%20Usage/

**Comment by olofk** [comment]
Unfortunately there is no one with time to maintain the LibreCores CI library, and are a number of other solutions available now, so I'm closing this.
